version: "3.1"
services:
    db:
        image: mysql:5.7
        container_name: symfony-redsocial-mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: redsocial
            MYSQL_PASSWORD: sa
            MYSQL_ROOT_PASSWORD: sa
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - mysql:/var/lib/mysql
        networks:
            - default
    symfony-redsocial:
        build: .
        ports: 
            - "80:80"
        volumes:
           # Define aquí los directorios que quieres hacer persistentes
            - assets:/var/www/html/public/assets
        links:
            - db:db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: sa
            MYSQL_ROOT_PASSWORD: sa 
volumes:
    mysql:
    assets:
networks:
    default: